version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "the-one"

  - package-ecosystem: "npm"
    directory: "/website"
    schedule:
      interval: "weekly"
    target-branch: "the-one"

  - package-ecosystem: "npm"
    directory: "/homepage"
    schedule:
      interval: "weekly"
    target-branch: "the-one"

  - package-ecosystem: "docker"
    directory: "/webserver"
    schedule:
      interval: "weekly"
    target-branch: "the-one"

  - package-ecosystem: "docker"
    directory: "/website"
    schedule:
      interval: "weekly"
    target-branch: "the-one"

  - package-ecosystem: "docker"
    directory: "/homepage"
    schedule:
      interval: "weekly"
    target-branch: "the-one"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "the-one"
